## Fat per dollar

This analysis looks at fat per dollar for different types of cheese sold at Walmart and Wholefoods, using [GroceryDB](https://github.com/Barabasi-Lab/GroceryDB) data.

### 1. Importing and setting up

In [11]:
import pandas as pd

df = pd.read_csv("GroceryDB_foods.csv")

### 2. Creating a subset of cheese data with name of the cheese, price, total fat and store, columns.

In [12]:
df_cheese = df.loc[
    df["harmonized single category"] == "cheese",
    ["harmonized single category", "name", "price", "Total Fat","store"]
]

### 3. Defining cheese categories

In [13]:
def categorize_cheese(name):
    name_lower = str(name).lower()

    if 'cheddar' in name_lower:
        return 'Cheddar'
    elif 'mozzarella' in name_lower:
        return 'Mozzarella'
    elif 'parmesan' in name_lower or 'parmigiano' in name_lower:
        return 'Parmesan'
    elif 'cream cheese' in name_lower or 'philadelphia' in name_lower:
        return 'Cream Cheese'
    elif 'goat' in name_lower or 'chevre' in name_lower:
        return 'Goat'
    elif 'brie' in name_lower:
        return 'Brie'
    elif 'feta' in name_lower:
        return 'Feta'
    elif 'gouda' in name_lower:
        return 'Gouda'
    elif 'blue' in name_lower or 'bleu' in name_lower:
        return 'Blue'
    elif 'american' in name_lower:
        return 'American'
    elif 'cottage' in name_lower:
        return 'Cottage'
    elif 'swiss' in name_lower:
        return 'Swiss'
    elif 'colby' in name_lower:
        return 'Colby'
    elif 'provolone' in name_lower:
        return 'Provolone'
    elif 'pepper jack' in name_lower:
        return 'Pepper Jack'
    elif 'ricotta' in name_lower:
        return 'Ricotta'
    else:
        return None

### 4. Categorising cheese by type

In [14]:

df_cheese["cheese_type"] = df_cheese["name"].apply(categorize_cheese)
df_cheese

,harmonized single category,name,price,Total Fat,store,cheese_type
4404,cheese,Kraft Deli Deluxe 2% Milk American Cheese Slic...,6.49,21.052632,Target,American
4405,cheese,Kraft Deli Deluxe American Cheese Slices - 16o...,6.49,31.578947,Target,American
4406,cheese,Kraft Singles American Cheese Slices - 16oz/24ct,3.99,18.421053,Target,American
4407,cheese,Kraft Singles American Cheese Slices - 16ct,3.99,19.047619,Target,American
4408,cheese,Kraft Singles 2% Milk American Cheese - 14.7oz...,3.99,13.157895,Target,American
...,...,...,...,...,...,...
6020,cheese,"Follow Your Heart American Cheese Slices, 7 oz...",4.87,22.500000,Walmart,American
6021,cheese,Sargento® Reserve Series™ Sliced Aged White Na...,2.98,35.000000,Walmart,Cheddar
6022,cheese,"Polly-O Mozzarella String Cheese, 16 ct. - 16....",4.98,17.857143,Walmart,Mozzarella
6023,cheese,DairyPure Smooth 4% Cottage Cheese with Smores...,1.28,700.000000,Walmart,Cottage
6024,cheese,Cracker Barrel Rich & Bold Extra Sharp Yellow ...,NaN,35.714286,Walmart,Cheddar

### 5. Removing the NAs

In [15]:
df_cheese = df_cheese[df_cheese['cheese_type'].notna()].copy()
df_cheese

,harmonized single category,name,price,Total Fat,store,cheese_type
4404,cheese,Kraft Deli Deluxe 2% Milk American Cheese Slic...,6.49,21.052632,Target,American
4405,cheese,Kraft Deli Deluxe American Cheese Slices - 16o...,6.49,31.578947,Target,American
4406,cheese,Kraft Singles American Cheese Slices - 16oz/24ct,3.99,18.421053,Target,American
4407,cheese,Kraft Singles American Cheese Slices - 16ct,3.99,19.047619,Target,American
4408,cheese,Kraft Singles 2% Milk American Cheese - 14.7oz...,3.99,13.157895,Target,American
...,...,...,...,...,...,...
6020,cheese,"Follow Your Heart American Cheese Slices, 7 oz...",4.87,22.500000,Walmart,American
6021,cheese,Sargento® Reserve Series™ Sliced Aged White Na...,2.98,35.000000,Walmart,Cheddar
6022,cheese,"Polly-O Mozzarella String Cheese, 16 ct. - 16....",4.98,17.857143,Walmart,Mozzarella
6023,cheese,DairyPure Smooth 4% Cottage Cheese with Smores...,1.28,700.000000,Walmart,Cottage
6024,cheese,Cracker Barrel Rich & Bold Extra Sharp Yellow ...,NaN,35.714286,Walmart,Cheddar

### 6. Selecting cheese sold only at Walmart and Whole Foods

In [ ]:
df_cheese = df_cheese[df_cheese['store'].isin(['Walmart', 'WholeFoods'])]
df_cheese

,harmonized single category,name,price,Total Fat,store,cheese_type
4775,cheese,"Block Cheese Packed In Brine Feta Cheese, 16 oz",7.49,10.582197,WholeFoods,Feta
4776,cheese,"Cheddar Style Goat Cheese Slices, 8 oz",6.99,34.782609,WholeFoods,Cheddar
4777,cheese,"Colby Jack Cheese, 8 oz",3.19,31.746592,WholeFoods,Colby
4778,cheese,"Colby Jack Cheese Sticks 6ct, 1 each",4.29,32.142857,WholeFoods,Colby
4779,cheese,"Colby Jack Cubes, 8 oz",3.99,32.142857,WholeFoods,Colby
...,...,...,...,...,...,...
6020,cheese,"Follow Your Heart American Cheese Slices, 7 oz...",4.87,22.500000,Walmart,American
6021,cheese,Sargento® Reserve Series™ Sliced Aged White Na...,2.98,35.000000,Walmart,Cheddar
6022,cheese,"Polly-O Mozzarella String Cheese, 16 ct. - 16....",4.98,17.857143,Walmart,Mozzarella
6023,cheese,DairyPure Smooth 4% Cottage Cheese with Smores...,1.28,700.000000,Walmart,Cottage
6024,cheese,Cracker Barrel Rich & Bold Extra Sharp Yellow ...,NaN,35.714286,Walmart,Cheddar

### 7. filtering the cheese with fat content between 0 and 50

In [17]:
df_cheese = df_cheese[(df_cheese['Total Fat'] >= 0) & (df_cheese['Total Fat'] < 50)]
df_cheese

,harmonized single category,name,price,Total Fat,store,cheese_type
4775,cheese,"Block Cheese Packed In Brine Feta Cheese, 16 oz",7.49,10.582197,WholeFoods,Feta
4776,cheese,"Cheddar Style Goat Cheese Slices, 8 oz",6.99,34.782609,WholeFoods,Cheddar
4777,cheese,"Colby Jack Cheese, 8 oz",3.19,31.746592,WholeFoods,Colby
4778,cheese,"Colby Jack Cheese Sticks 6ct, 1 each",4.29,32.142857,WholeFoods,Colby
4779,cheese,"Colby Jack Cubes, 8 oz",3.99,32.142857,WholeFoods,Colby
...,...,...,...,...,...,...
6019,cheese,Philadelphia Dips Spinach & Artichoke Cream Ch...,3.28,16.666667,Walmart,Cream Cheese
6020,cheese,"Follow Your Heart American Cheese Slices, 7 oz...",4.87,22.500000,Walmart,American
6021,cheese,Sargento® Reserve Series™ Sliced Aged White Na...,2.98,35.000000,Walmart,Cheddar
6022,cheese,"Polly-O Mozzarella String Cheese, 16 ct. - 16....",4.98,17.857143,Walmart,Mozzarella
6024,cheese,Cracker Barrel Rich & Bold Extra Sharp Yellow ...,NaN,35.714286,Walmart,Cheddar

### 8. Copying price and total fat into a new dataset and then filtering price

In [18]:
priceVfat = df_cheese.dropna(subset=['price', 'Total Fat']).copy()
priceVfat = priceVfat [priceVfat ['price'] > 0]
priceVfat

,harmonized single category,name,price,Total Fat,store,cheese_type
4775,cheese,"Block Cheese Packed In Brine Feta Cheese, 16 oz",7.49,10.582197,WholeFoods,Feta
4776,cheese,"Cheddar Style Goat Cheese Slices, 8 oz",6.99,34.782609,WholeFoods,Cheddar
4777,cheese,"Colby Jack Cheese, 8 oz",3.19,31.746592,WholeFoods,Colby
4778,cheese,"Colby Jack Cheese Sticks 6ct, 1 each",4.29,32.142857,WholeFoods,Colby
4779,cheese,"Colby Jack Cubes, 8 oz",3.99,32.142857,WholeFoods,Colby
...,...,...,...,...,...,...
6017,cheese,Great Value Deli Style Sliced Non-Smoked Provo...,4.22,26.315789,Walmart,Provolone
6019,cheese,Philadelphia Dips Spinach & Artichoke Cream Ch...,3.28,16.666667,Walmart,Cream Cheese
6020,cheese,"Follow Your Heart American Cheese Slices, 7 oz...",4.87,22.500000,Walmart,American
6021,cheese,Sargento® Reserve Series™ Sliced Aged White Na...,2.98,35.000000,Walmart,Cheddar
6022,cheese,"Polly-O Mozzarella String Cheese, 16 ct. - 16....",4.98,17.857143,Walmart,Mozzarella

### 9.Calculating fat per dollar = Total Fat/price

In [19]:
priceVfat['fat_per_dollar'] = priceVfat['Total Fat'] / priceVfat['price']
priceVfat

,harmonized single category,name,price,Total Fat,store,cheese_type,fat_per_dollar
4775,cheese,"Block Cheese Packed In Brine Feta Cheese, 16 oz",7.49,10.582197,WholeFoods,Feta,1.412843
4776,cheese,"Cheddar Style Goat Cheese Slices, 8 oz",6.99,34.782609,WholeFoods,Cheddar,4.976053
4777,cheese,"Colby Jack Cheese, 8 oz",3.19,31.746592,WholeFoods,Colby,9.951910
4778,cheese,"Colby Jack Cheese Sticks 6ct, 1 each",4.29,32.142857,WholeFoods,Colby,7.492507
4779,cheese,"Colby Jack Cubes, 8 oz",3.99,32.142857,WholeFoods,Colby,8.055854
...,...,...,...,...,...,...,...
6017,cheese,Great Value Deli Style Sliced Non-Smoked Provo...,4.22,26.315789,Walmart,Provolone,6.235969
6019,cheese,Philadelphia Dips Spinach & Artichoke Cream Ch...,3.28,16.666667,Walmart,Cream Cheese,5.081301
6020,cheese,"Follow Your Heart American Cheese Slices, 7 oz...",4.87,22.500000,Walmart,American,4.620123
6021,cheese,Sargento® Reserve Series™ Sliced Aged White Na...,2.98,35.000000,Walmart,Cheddar,11.744966
6022,cheese,"Polly-O Mozzarella String Cheese, 16 ct. - 16....",4.98,17.857143,Walmart,Mozzarella,3.585772

### 10. Taking the median fat per dollar value for each cheese type

In [20]:
priceVfat = priceVfat.groupby('cheese_type').agg(
      fat_per_dollar=('fat_per_dollar', 'median')).sort_values('fat_per_dollar', ascending= False)
priceVfat

              fat_per_dollar
cheese_type
Colby               8.978452
Provolone           7.686698
Cheddar             7.306889
Gouda               7.162232
Parmesan            6.811902
Blue                6.778431
Pepper Jack         6.710952
Swiss               6.495309
Cream Cheese        5.547337
Brie                4.687417
Feta                4.277823
Mozzarella          4.236456
American            4.180543
Goat                3.886904
Ricotta             1.888014
Cottage             1.005632