## Cheese price divide

This analysis looks at the price difference for different types of cheese sold at Walmart and Wholefoods, using [GroceryDB](https://github.com/Barabasi-Lab/GroceryDB) data.

### 1. Importing and setting up

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("GroceryDB_foods.csv")

### 2. Creating a subset of cheese data with name of the cheese, price, total fat and store, columns.

In [2]:

df_cheese = df.loc[
    df["harmonized single category"] == "cheese",
    ["harmonized single category", "name", "store", "price"]
]
df_cheese

,harmonized single category,name,store,price
4404,cheese,Kraft Deli Deluxe 2% Milk American Cheese Slic...,Target,6.49
4405,cheese,Kraft Deli Deluxe American Cheese Slices - 16o...,Target,6.49
4406,cheese,Kraft Singles American Cheese Slices - 16oz/24ct,Target,3.99
4407,cheese,Kraft Singles American Cheese Slices - 16ct,Target,3.99
4408,cheese,Kraft Singles 2% Milk American Cheese - 14.7oz...,Target,3.99
...,...,...,...,...
6020,cheese,"Follow Your Heart American Cheese Slices, 7 oz...",Walmart,4.87
6021,cheese,Sargento® Reserve Series™ Sliced Aged White Na...,Walmart,2.98
6022,cheese,"Polly-O Mozzarella String Cheese, 16 ct. - 16....",Walmart,4.98
6023,cheese,DairyPure Smooth 4% Cottage Cheese with Smores...,Walmart,1.28
6024,cheese,Cracker Barrel Rich & Bold Extra Sharp Yellow ...,Walmart,NaN

### 3. Defining cheese categories

In [3]:
def categorize_cheese(name):
    name_lower = str(name).lower()

    if 'cheddar' in name_lower:
        return 'Cheddar'
    elif 'mozzarella' in name_lower:
        return 'Mozzarella'
    elif 'parmesan' in name_lower or 'parmigiano' in name_lower:
        return 'Parmesan'
    elif 'cream cheese' in name_lower or 'philadelphia' in name_lower:
        return 'Cream Cheese'
    elif 'goat' in name_lower or 'chevre' in name_lower:
        return 'Goat'
    elif 'brie' in name_lower:
        return 'Brie'
    elif 'feta' in name_lower:
        return 'Feta'
    elif 'gouda' in name_lower:
        return 'Gouda'
    elif 'blue' in name_lower or 'bleu' in name_lower:
        return 'Blue'
    elif 'american' in name_lower:
        return 'American'
    elif 'cottage' in name_lower:
        return 'Cottage'
    elif 'swiss' in name_lower:
        return 'Swiss'
    elif 'colby' in name_lower:
        return 'Colby'
    elif 'provolone' in name_lower:
        return 'Provolone'
    elif 'pepper jack' in name_lower:
        return 'Pepper Jack'
    elif 'ricotta' in name_lower:
        return 'Ricotta'
    else:
        return None

### 4. Categorising cheese by type

In [4]:
df_cheese["cheese_type"] = df_cheese["name"].apply(categorize_cheese)

### 5. Removing the NAs

In [6]:
df_cheese = df_cheese[df_cheese['cheese_type'].notna()]
df_cheese

,harmonized single category,name,store,price,cheese_type
4404,cheese,Kraft Deli Deluxe 2% Milk American Cheese Slic...,Target,6.49,American
4405,cheese,Kraft Deli Deluxe American Cheese Slices - 16o...,Target,6.49,American
4406,cheese,Kraft Singles American Cheese Slices - 16oz/24ct,Target,3.99,American
4407,cheese,Kraft Singles American Cheese Slices - 16ct,Target,3.99,American
4408,cheese,Kraft Singles 2% Milk American Cheese - 14.7oz...,Target,3.99,American
...,...,...,...,...,...
6020,cheese,"Follow Your Heart American Cheese Slices, 7 oz...",Walmart,4.87,American
6021,cheese,Sargento® Reserve Series™ Sliced Aged White Na...,Walmart,2.98,Cheddar
6022,cheese,"Polly-O Mozzarella String Cheese, 16 ct. - 16....",Walmart,4.98,Mozzarella
6023,cheese,DairyPure Smooth 4% Cottage Cheese with Smores...,Walmart,1.28,Cottage
6024,cheese,Cracker Barrel Rich & Bold Extra Sharp Yellow ...,Walmart,NaN,Cheddar

### 6. Filter to include cheese from only Walmart and Whole Foods

In [ ]:
df_cheese = df_cheese[df_cheese['store'].isin(['Walmart', 'WholeFoods'])]
df_cheese

,harmonized single category,name,store,price,cheese_type
4775,cheese,"Block Cheese Packed In Brine Feta Cheese, 16 oz",WholeFoods,7.49,Feta
4776,cheese,"Cheddar Style Goat Cheese Slices, 8 oz",WholeFoods,6.99,Cheddar
4777,cheese,"Colby Jack Cheese, 8 oz",WholeFoods,3.19,Colby
4778,cheese,"Colby Jack Cheese Sticks 6ct, 1 each",WholeFoods,4.29,Colby
4779,cheese,"Colby Jack Cubes, 8 oz",WholeFoods,3.99,Colby
...,...,...,...,...,...
6020,cheese,"Follow Your Heart American Cheese Slices, 7 oz...",Walmart,4.87,American
6021,cheese,Sargento® Reserve Series™ Sliced Aged White Na...,Walmart,2.98,Cheddar
6022,cheese,"Polly-O Mozzarella String Cheese, 16 ct. - 16....",Walmart,4.98,Mozzarella
6023,cheese,DairyPure Smooth 4% Cottage Cheese with Smores...,Walmart,1.28,Cottage
6024,cheese,Cracker Barrel Rich & Bold Extra Sharp Yellow ...,Walmart,NaN,Cheddar

### 7. Group into cheese types, stores and median price

In [ ]:
df_cheese = df_cheese.groupby(['cheese_type','store'])['price'].median().unstack()

### 8. Remove NA's again

In [9]:
df_cheese= df_cheese.dropna()

### 9. Calculating the price difference and percentage price difference for Walmart Vs Wholefoods

In [10]:
df_cheese['difference'] = (df_cheese['WholeFoods'] - df_cheese['Walmart']).round(2)
df_cheese['pct_difference'] = (((df_cheese['WholeFoods'] / df_cheese['Walmart']) - 1) * 100).round(2)
df_cheese = df_cheese.sort_values('difference', ascending=False)
df_cheese

store         Walmart  WholeFoods  difference  pct_difference
cheese_type
Gouda           3.180       16.99       13.81          434.28
Blue            2.900       14.99       12.09          416.90
Brie            4.690       11.99        7.30          155.65
Swiss           2.915        7.99        5.08          174.10
Goat            3.220        6.99        3.77          117.08
Provolone       2.930        6.64        3.71          126.62
Feta            3.980        6.99        3.01           75.63
Parmesan        3.440        5.99        2.55           74.13
Ricotta         3.490        5.99        2.50           71.63
Cottage         1.760        3.99        2.23          126.70
Cheddar         3.275        5.29        2.02           61.53
Mozzarella      3.975        5.89        1.92           48.18
Pepper Jack     3.440        5.29        1.85           53.78
American        4.980        5.99        1.01           20.28
Colby           3.530        4.29        0.76           21.53
Cream Cheese    3.380        3.59        0.21            6.21

### 10. Calculating the median Price difference

In [11]:
median = df_cheese['difference'].median()
median

np.float64(2.525)